config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'posts#index'
  get '/posts/new' => 'posts#new', as: :new_post_path
  post '/posts' => 'posts#create'
  delete '/posts/:id' => 'posts#destroy'
  get '/signup' => 'users#new'
  get '/user/new' => 'users#new'
  post '/user' => 'users#create', as: :user
  post '/user' => 'users#create', as: :users
  patch '/user' => 'users#update'
  get '/user/edit' => 'users#show'
  get 'tippen' => 'tipps#index'
  get '/tippen/:id' => 'tipps#show', as: :tipps
  post '/tippen/:id' => 'tipps#create', as: :new_tipps
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/admin' => 'admins#show'
  get '/admin/:id' => 'admins#update'
  resources :overviews
  post '/calculate' => 'matchday#calculate', as: :calculate
  get '/cronCalculate' => 'matchday#checkForFinishedMatchday'
  
  
  get '/' => 'posts#index'
end

app/views/admins/show.html.haml
-if flash.notice
    %div{:id=>"Flash", :class=>"success"} #{flash.notice}
-if flash.alert
    %div{:id=>"Flash", :class=>"alert"} #{flash.alert}
<br /><br />
="Aktueller Spieltag: #{@currentMatchday['GroupOrderID']}"
<br />
="fertig berechnet: #{@lastCalculated}"
<br />
<br />
= form_tag calculate_path do
    %select{:name => 'matchdaySelected'}
        -(1..34).each do |i|
            %option{:value=>"#{i}"} Spieltag #{i}
        %option{:value=>"all"} alle Spieltage
    =submit_tag "berechnen"
<br /><br />
%select{:onchange=>"changeAdminUser(this)"}
    -@users.each do |user|
        -if user==current_user
            %option{:value=>"/admin/#{user.id}", :selected=>true} #{user.username}
        -else
            %option{:value=>"/admin/#{user.id}"} #{user.username}
<br>
-@results.each do |result|
    =result.year
    =result.user_id
    =result.matchday
    =result.result
    <br>
<br>
<hr>
-@users.each do |user|
    =user.id
    =user.nickname
    =user.username
    =user.password_digest
    =user.first_name
    =user.last_name
    <br>
<br>
<hr>
-@tipps.each do|tipp|
    =tipp.user_id
    =tipp.spiel
    =tipp.tipp1
    =tipp.tipp2
    =tipp.created_at
    <br>