config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'posts#index'
  get '/posts/new' => 'posts#new', as: :new_post_path
  post '/posts' => 'posts#create'
  delete '/posts/:id' => 'posts#destroy'
  get '/signup' => 'users#new'
  get '/user/new' => 'users#new'
  post '/user' => 'users#create', as: :user
  post '/user' => 'users#create', as: :users
  patch '/user' => 'users#update'
  get '/user/edit' => 'users#show'
  get 'tippen' => 'tipps#index'
  get '/tippen/:id' => 'tipps#show', as: :tipps
  post '/tippen/:id' => 'tipps#create', as: :new_tipps
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/admin' => 'admins#show'
  get '/admin/:id' => 'admins#update'
  resources :overviews
  post '/calculate' => 'matchday#calculate', as: :calculate
  get '/cronCalculate' => 'matchday#checkForFinishedMatchday'
  
  
  get '/' => 'posts#index'
end

app/models/tipp.rb
class Tipp < ActiveRecord::Base
    belongs_to :user
end

app/controllers/tipps_controller.rb
class TippsController < ApplicationController
    before_action :require_user
    def index
		currentMatchday=[]
		
		res = open("#{@@URI}#{@@API_CURR}/#{@@LEAGUE}").read
		currentMatchday = JSON.parse res
		@test = currentMatchday
		if currentMatchday['GroupOrderID']
			redirect_to "/tippen/#{currentMatchday['GroupOrderID']}"
		end
	end
	
	def show
	    @tipp=Tipp.new
		@currentMatchday = params['id']
		if @currentMatchday.to_i>34 || @currentMatchday.to_i<1
			redirect_to "/tippen"
		end
		@games=[]
		res = open("#{@@URI}#{@@API_PATH}/#{@@LEAGUE}/#{@@SAISON}/#{@currentMatchday}").read
		@games = JSON.parse res
		@previousGames={}
		@oneActive = false
		@games.each do |game|
			@oneActive = true if game['MatchIsFinished'] == false
		    t = DateTime.parse(game['MatchDateTime'])
		    oldTipp = Tipp.find_by user_id: session[:user_id], spiel: game['MatchID']
			if oldTipp
		    	game['class'] = ""
		        game['tipp1'] = oldTipp.tipp1
		        game['tipp2'] = oldTipp.tipp2
		        if game['MatchIsFinished'] && game['MatchResults'][0]
		        	if game['MatchResults'][game['MatchResults'].length-1]['PointsTeam1'] == oldTipp.tipp1 && game['MatchResults'][game['MatchResults'].length-1]['PointsTeam2'] == oldTipp.tipp2
		        		game['class'] = "greenCell"
		        	else
		        		if (oldTipp.tipp1 != nil && oldTipp.tipp2 != nil) && game['MatchResults'][game['MatchResults'].length-1]['PointsTeam2'] - game['MatchResults'][game['MatchResults'].length-1]['PointsTeam1'] == oldTipp.tipp2 - oldTipp.tipp1
		        			game['class'] = "yellowCell"
		        		else
		        			game['class'] = 'redCell'
		        		end
		        	end
		        end
		    else
		    	if game['MatchIsFinished']
		    		game['class'] = 'redCell'
		    	end
		    	
		    end
		    game['date'] = t.strftime("%d.%m.%Y")
		    game['time'] = t.strftime("%H:%M")
		    n = Time.now
		    n = n - n.gmt_offset + 7200
		    game['active'] = t>n
		    
		    @previousGames[game['Team1']['TeamId']] = {}
		    @previousGames[game['Team2']['TeamId']] = {}
		end
		
		myMatchday = @currentMatchday.to_i
		mySaison = @@SAISON.to_i
		5.times do |i|
			myMatchday -= 1
			if myMatchday == 0
				myMatchday = 34
				mySaison -= 1
			end
			
			
			tempGames=[]
			res = open("#{@@URI}#{@@API_PATH}/#{@@LEAGUE}/#{mySaison}/#{myMatchday}").read
			tempGames = JSON.parse res
			tempGames.each do |tempGame|
				t = DateTime.parse(tempGame['MatchDateTime'])
				if @previousGames[tempGame['Team1']['TeamId']]
					@previousGames[tempGame['Team1']['TeamId']]["#{i}"] = {}
					@previousGames[tempGame['Team1']['TeamId']]["#{i}"]['date'] = t.strftime("%d.%m.%Y")
					@previousGames[tempGame['Team1']['TeamId']]["#{i}"]['icon1'] = tempGame['Team1']['TeamIconUrl']
					@previousGames[tempGame['Team1']['TeamId']]["#{i}"]['icon2'] = tempGame['Team2']['TeamIconUrl']
					if tempGame['MatchResults'][0]
						@previousGames[tempGame['Team1']['TeamId']]["#{i}"]['result1'] = tempGame['MatchResults'][tempGame['MatchResults'].length-1]['PointsTeam1']
						@previousGames[tempGame['Team1']['TeamId']]["#{i}"]['result2'] = tempGame['MatchResults'][tempGame['MatchResults'].length-1]['PointsTeam2']
					else
						@previousGames[tempGame['Team1']['TeamId']]["#{i}"]['result1'] = ""
						@previousGames[tempGame['Team1']['TeamId']]["#{i}"]['result2'] = ""
					end
				end
				
				if @previousGames[tempGame['Team2']['TeamId']]
					@previousGames[tempGame['Team2']['TeamId']]["#{i}"] = {}
					@previousGames[tempGame['Team2']['TeamId']]["#{i}"]['date'] = t.strftime("%d.%m.%Y")
					@previousGames[tempGame['Team2']['TeamId']]["#{i}"]['icon1'] = tempGame['Team1']['TeamIconUrl']
					@previousGames[tempGame['Team2']['TeamId']]["#{i}"]['icon2'] = tempGame['Team2']['TeamIconUrl']
					if tempGame['MatchResults'][0]
						@previousGames[tempGame['Team2']['TeamId']]["#{i}"]['result1'] = tempGame['MatchResults'][tempGame['MatchResults'].length-1]['PointsTeam1']
						@previousGames[tempGame['Team2']['TeamId']]["#{i}"]['result2'] = tempGame['MatchResults'][tempGame['MatchResults'].length-1]['PointsTeam2']
					else
						@previousGames[tempGame['Team2']['TeamId']]["#{i}"]['result1'] = ""
						@previousGames[tempGame['Team2']['TeamId']]["#{i}"]['result2'] = ""
					end
				end
			end
		end
		
	end
	
    def new
        @tipp=Tipp.new()
    end
    
    def create
        allSaved=true
        for i in 0..8
        	#check if tipp has already been entered for this game
            oldTipp = Tipp.find_by user_id: session[:user_id], spiel: params['tipp']['spiel'][i]
            if oldTipp
                tipp = oldTipp
            else
            	tipp = Tipp.new
            	tipp.user_id = session[:user_id]
            	tipp.spiel = params['tipp']['spiel'][i]
            end
            tipp.tipp1 = params['tipp']['tipp1'][i]
            tipp.tipp2 = params['tipp']['tipp2'][i]
            
            
            
            #save new tipp
            if tipp.tipp1!=nil || tipp.tipp2!=nil || oldTipp
                if !tipp.save #in case of an error whilst saving
                    allSaved=false
                end
            end
        end
        if allSaved
            flash.notice = "Tipps erfolgreich gespeichert"
        else
            flash.alert = "Fehler beim Speichern"
        end
        redirect_to "/tippen/"+params[:id]
    end
    
    private
	def tipp_params
		params.require(:tipp).permit(:user_id, :spiel, :tipp1, :tipp2)
	end
end

app/views/tipps/new.html.haml
= form_for @tipp do |f|
	= f.number_field :tipp1, multiple:true
	= f.number_field :tipp2, multiple:true
	= f.number_field :tipp1, multiple:true
	= f.number_field :tipp2, multiple:true
	= f.submit "Create Tipp"

app/views/tipps/show.html.haml
-if flash.notice
    %div{:id=>"Flash", :class=>"success"} #{flash.notice}
-if flash.alert
    %div{:id=>"Flash", :class=>"alert"} #{flash.alert}
.row
    .col-xs-1 &nbsp;
    .col-xs-10{:class => "text-right"}
        %select{:onchange=>"changeMatchday(this)"}
            -(1..34).each do |i|
                -if i==@currentMatchday.to_i
                    %option{:value=>"#{tipps_path(i)}", :selected=>true} Spieltag #{i}
                -else
                    %option{:value=>"#{tipps_path(i)}"} Spieltag #{i}
%br
=form_for @tipp do |f|
    .row
        .col-xs-1 &nbsp;
        .col-xs-10
            %table{:border=>"1", :id=>"ContentTable", :width => "100%"}
                %tr{:align => 'center'}
                    %th{:align => 'centre'} Datum
                    %th Uhrzeit
                    %th Heim
                    %th Gast
                    %th Ergebnis
                    %th Tipp
                -@games.each do |game|
                    %tr
                        %td{:align => 'center'} #{game['date']}
                        %td{:align => 'center'} #{game['time']}
                        %td
                            =image_tag("#{game['Team1']['TeamIconUrl']}", size: "20")
                            &nbsp;
                            ="#{game['Team1']['TeamName']}"
                        %td
                            =image_tag("#{game['Team2']['TeamIconUrl']}", size: "20")
                            &nbsp;
                            ="#{game['Team2']['TeamName']}"
                        %td{:align => 'center'}
                            -if game['MatchResults'][0]
                                =game['MatchResults'][game['MatchResults'].length-1]['PointsTeam1']
                                &#58
                                =game['MatchResults'][game['MatchResults'].length-1]['PointsTeam2']
                            -else
                                &nbsp;
                        %td{:align => 'center', :class => game['class']}
                            = f.hidden_field :spiel, :value=>game['MatchID'], multiple:true
                            -if game['active'] or (current_user.admin?)
                                = f.text_field :tipp1, multiple:true, :value=>game['tipp1'], :pattern=>"[0-9]*", :title=>"max. 2-stellige Ergebnisse", :class=>"tippEntry", :onfocus => "showLastResults(#{game['MatchID']})"
                            -else
                                = f.hidden_field :tipp1, multiple:true, :value=>game['tipp1']
                                = game['tipp1']
                            &#58
                            -if game['active'] or (current_user.admin?)
                                = f.text_field :tipp2, multiple:true, :value=>game['tipp2'], :pattern=>"[0-9]*", :title=>"max. 2-stellige Ergebnisse", :class=>"tippEntry", :onfocus => "showLastResults(#{game['MatchID']})"
                            -else
                                = f.hidden_field :tipp2, multiple:true, :value=>game['tipp2']
                                = game['tipp2']
            %br
    .row
        .col-xs-1 &nbsp;
        .col-xs-10{:class => "text-right"}
            =f.submit "speichern" if @oneActive  or (current_user.admin?)
%br
%div{:class => 'HeaderLastResults'}= "letzte Ergebnisse" if @oneActive
%br
-@games.each do |game|
    %div{:id => "#{game['MatchID']}", :class => "previousResults", :hidden => true}
        .row
            .col-xs-6
                -@previousGames[game['Team1']['TeamId']].each do |prev|
                    .row
                        .col-xs-2 &nbsp;
                        .col-xs-2 
                            ="#{prev[1]['date']}"
                        .col-xs-6
                            =image_tag(prev[1]['icon1'], size: "20")
                            &nbsp;&#58&nbsp;
                            =image_tag(prev[1]['icon2'], size: "20")
                            &nbsp;-&nbsp;
                            ="#{prev[1]['result1']} : #{prev[1]['result2']}"
                        .col-xs-2 &nbsp;
            .col-xs-6
                -@previousGames[game['Team2']['TeamId']].each do |prev|
                    .row
                        .col-xs-4 &nbsp;
                        .col-xs-2 
                            ="#{prev[1]['date']}"
                        .col-xs-6
                            =image_tag(prev[1]['icon1'], size: "20")
                            &nbsp;&#58&nbsp;
                            =image_tag(prev[1]['icon2'], size: "20")
                            &nbsp;-&nbsp;
                            ="#{prev[1]['result1']} : #{prev[1]['result2']}"