config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'posts#index'
  get '/posts/new' => 'posts#new', as: :new_post_path
  post '/posts' => 'posts#create'
  delete '/posts/:id' => 'posts#destroy'
  get '/signup' => 'users#new'
  get '/user/new' => 'users#new'
  post '/user' => 'users#create', as: :user
  post '/user' => 'users#create', as: :users
  patch '/user' => 'users#update'
  get '/user/edit' => 'users#show'
  get 'tippen' => 'tipps#index'
  get '/tippen/:id' => 'tipps#show', as: :tipps
  post '/tippen/:id' => 'tipps#create', as: :new_tipps
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/admin' => 'admins#show'
  get '/admin/:id' => 'admins#update'
  resources :overviews
  post '/calculate' => 'matchday#calculate', as: :calculate
  get '/cronCalculate' => 'matchday#checkForFinishedMatchday'
  
  
  get '/' => 'posts#index'
end

app/controllers/overviews_controller.rb
class OverviewsController < ApplicationController
	include OverviewsHelper
	require 'open-uri'
	
	def index
		currentMatchday=[]
		url = URI.parse(@@URI)
		
		res = open("#{@@URI}#{@@API_CURR}/#{@@LEAGUE}").read
		#res = Net::HTTP.start(url.host,url.port) do |http|
		#  http.get("#{@@API_CURR}/#{@@LEAGUE}")
		#end
		
		print res
		
		currentMatchday = JSON.parse res
		#currentMatchday = {"GroupOrderID"=>34}
		@test = currentMatchday
		if currentMatchday['GroupOrderID']
			redirect_to "/overviews/#{currentMatchday['GroupOrderID']}"
		end
	end
	
	def show
		@currentMatchday = params['id']
		if @currentMatchday.to_i>34 || @currentMatchday.to_i<1
			redirect_to "/overviews"
		end
		@games=[]
		#url = URI.parse(@@URI)
		#res = Net::HTTP.start(url.host,url.port) do |http|
		#  http.get("#{@@API_PATH}/#{@@LEAGUE}/#{@@SAISON}/#{@currentMatchday}")
		#end
		res = open("#{@@URI}#{@@API_PATH}/#{@@LEAGUE}/#{@@SAISON}/#{@currentMatchday}").read
		@games = JSON.parse res
		@users = User.all
		@games.each do |game|
			res1, res2 = getResult(game)
		    t = DateTime.parse(game['MatchDateTime'])
		    n = Time.now
		    n = n - n.gmt_offset + 7200
		    game['active'] = t<n
		    @users.each do |user|
		       game[user.id] = []
		       #put result per user in game JSON
		       tipp = user.tipps.find_by(:user_id=>user.id, :spiel=> game['MatchID']) 
		       if tipp
		       		if  user==current_user || game['active']
		           		game[user.id][0] = "#{tipp.tipp1.to_s} : #{tipp.tipp2.to_s}"
		           	else
		           		game[user.id][0] = "n/a"
		           	end
		           #put class information for cell and costs for player/game in game JSON
		           if game['MatchIsFinished'] #if game has ended
                        if tipp.tipp1==res1 && tipp.tipp2 == res2
                            game[user.id][1]="tippCell greenCell"
                            game[user.id][2]=-0.5
                        else 
                            if (tipp.tipp1 && tipp.tipp2) && tipp.tipp2-tipp.tipp1 == res2-res1
                                game[user.id][1]="tippCell yellowCell"
                                game[user.id][2]=-0.25
                            else
                                game[user.id][1]="tippCell redCell"
                                game[user.id][2]=0.25
                            end
                        end
		           else
		                game[user.id][1] = "tippCell"
		                game[user.id][2] = 0.25
		           end
		       else
		           if game['MatchIsFinished'] #if game has ended
		                game[user.id][1] = "tippCell redCell"
		                game[user.id][2] = 0.25
		           else
		                game[user.id][0] = " "
		                game[user.id][1] = "tippCell"
		                game[user.id][2] = 0.25
		           end
		       end
		       
		       
		    end
		end
		
		@resultPerUser=[]
		@users.each do |user|
			#r = Result.find_by year: @@SAISON, user_id: user.id	
			upperEnd = params[:id].to_f-1
			r = Result.where(year: @@SAISON, user_id: user.id, matchday: 0..upperEnd).all
			res = 0.0
			if r != nil
				r.each do |matchdayResult|
					res += matchdayResult.result
				end
			end
			@resultPerUser[user.id] = res
		end
	end
end

app/helpers/overviews_helper.rb
module OverviewsHelper
    
    def getResult(game)
        resultGroup = game['MatchResults']
        resultGroup.each do |group|
            if group['ResultName'] == 'Endergebnis'
                return group['PointsTeam1'],group['PointsTeam2']
            end
        end
        resultGroup.each do |group|
            if group['ResultName'] != 'Halbzeitergebnis'
                return group['PointsTeam1'],group['PointsTeam2']
            end
        end
        resultGroup.each do |group|
            if group['ResultName'] == 'Halbzeitergebnis'
                return group['PointsTeam1'],group['PointsTeam2']
            end
        end
    end
end

app/views/overviews/index.html.haml
.content #{@test}


app/views/overviews/show.html.haml
.row
	.col-xs-1 &nbsp;
	.col-xs-10{:class => 'text-right'}
		%select{:onchange=>"changeMatchday(this)"}
			-(1..34).each do |i|
				-if i==@currentMatchday.to_i
					%option{:value=>"#{overview_path(i)}", :selected=>true} Spieltag #{i}
				-else
					%option{:value=>"#{overview_path(i)}"} Spieltag #{i}
%br
.row
	.col-md-1 &nbsp;
	.col-xs-10
		%table{:border=>"0", :id=>"ContentTable", :width => "100%"}
			%tr
				%td{:class => "emptyOverviewCell"} &nbsp;
				-@games.each do |game|
					-res1, res2 = getResult(game)
					%td{:class=>"gameHeader"}
						=image_tag("#{game['Team1']['TeamIconUrl']}", size: "20")
						&#58
						=image_tag("#{game['Team2']['TeamIconUrl']}", size: "20")
						<br />
						=res1
						&#58
						=res2
				%td{:align => "center", :valign => 'bottom', :style => "padding:2px;padding-bottom:0px;"} Aktuell
				%td{:align => "center", :valign => 'bottom', :style => "padding:2px;padding-bottom:0px;"} Bisher
				%td{:align => "center", :valign => 'bottom', :style => "padding:2px;padding-bottom:0px;"} Gesamt
			-counter=0
			-@users.each do |user|
				-if user==current_user || @currentMatchday.to_i < 31
					-counter += 1
					%tr
						%td{:class=>"cell#{counter%2} userCol1"} 
							-if user.nickname != ""
								=user.nickname
							-else
								=user.username
						-total=0.0
						-@games.each do |game|
							-total+=game[user.id][2]
							%td{:class => "cell#{counter%2} #{game[user.id][1]}"} #{game[user.id][0]}
						-if total <= 0.0
							-total = 0.0
						%td{:class=>"cell#{counter%2} text-right"} #{number_with_delimiter(number_with_precision(total,precision: 2),separator: ",").to_s} €
						%td{:class=>"cell#{counter%2} text-right"} #{number_with_delimiter(number_with_precision(@resultPerUser[user.id],precision: 2),separator: ",").to_s} €
						%td{:class=>"cell#{counter%2} text-right"} #{number_with_delimiter(number_with_precision((total+@resultPerUser[user.id]),precision: 2),separator: ",").to_s} €
/ =@games[0]


